#端口号
server:
  port: 8888
spring:
  datasource:
    druid:
#     url: jdbc:mysql://rm-uf6a641x61h7u6261vo.mysql.rds.aliyuncs.com:3306/xqdev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai
#     username: xiaoqingroot
#     password: xiaoqing!2020
      url: jdbc:mysql://121.37.141.16:3306/xqsh?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
#      url: jdbc:mysql://132.232.54.221:3306/xqsh?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#      username: root
#      password: so123
#      url: jdbc:mysql://localhost:3306/activity?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#      username: root
#      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
#      type: com.alibaba.druid.pool.DruidDataSource
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 5
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 最小连接池数量
      min-idle: 5
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      web:
        username: admin
        password: 123456
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 121.37.141.16
#    host: www.tangcc.xyz
#    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
#    password: so123
    password:
    # 连接超时时间（毫秒）
    timeout: 3000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 50
      #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.weilai9.dao.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    # map key为null时也返回
    call-setters-on-nulls: true

#token有效周期，周期内使用，自动重置有效时间，周期内未使用，过期，单位（秒）
jwt:
  expire:
    # 7天
    time: 604800

#系统消息超时未读，自动已读时间 单位（小时）
msg:
  sys:
    expire:
      # 30天
      time: 720

#阿里云
aliyun:
  #短信SMS
  sms:
    regionId: cn-hangzhou
    endpoint: cn-hangzhou
    product: Dysmsapi
    signName: 鲜小厨
    accessKeyId: LTAI108qwuldrzrT
    accessKeySecret: 5uv4uThu4d7mkyhU1vYZ3oJuZfxO1t
  #图片OSS
  oss:
    bucket: xxw-xxc
    endpoint: oss-cn-chengdu.aliyuncs.com
    accessKeyId: LTAI108qwuldrzrT
    accessKeySecret: 5uv4uThu4d7mkyhU1vYZ3oJuZfxO1t
    expireTime: 1800
    sts:
      roleArn: acs:ram::1642630753164124:role/admin
      stsTokenExpireTime: 900
#七牛直播配置
qiniu:
  video:
    live:
      #key
      accessKey: XdYaXUJjvELWO7NNWcDC-O3JAmarBcccibUTNqeT
      #secret
      secretKey: hGditfn8uXBZfIChr6--S-fkHbl052WoxiSWnyvv
      #直播空间名称
      hubName: sqshtest
      #推流地址
      publishDomain: pili-publish.appnanjing.com
      #播放地址
      liveDomain: pili-live-rtmp.appnanjing.com

#友盟推送
push:
  umeng:
    android:
      key: androidkey
      secret: androidsecret
    ios:
      key: ioskey
      secret: iosSecret
#swagger
knife4j:
  basic:
    # true 不会执行自动初始化接口数据
    enable: false
    username: weilai9
    password: 123456

#定时器连接池
scheduled:
  pool-size: 10

#logback
logging:
  config: classpath:logback-spring.xml
wx:
  #小程序配置
  miniapp:
    configs:
      #小程序的APPID,测试小程序
      - appid: wx092858e88f3b46f1
        #（小程序的secret）
        secret: 334b3c8f4bc226b95423975bacf947ff
        #微信小程序消息服务器配置的token,未使用
        token:
        #微信小程序消息服务器配置的EncodingAESKey,未使用
        aesKey:
        msgDataFormat: JSON
  #微信支付配置
  pay:
    #微信公众号或者小程序等的appid
    appId: wx092858e88f3b46f1
    #微信支付商户号
    mchId: 1566272871
    #微信支付商户密钥
    mchKey: GSVv9ou04fVoNuxAjVJI1hubVwPeXBCk
    #支付回调地址
    notifyUrl: www.baidu.com
    #服务商模式下的子商户公众账号ID
    subAppId:
    #服务商模式下的子商户号
    subMchId:
    # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
    keyPath: D:\code\houtai\web\src\main\resources\hejinlo\apiclient_cert.p12